---
extends: eslint:recommended
env:
  es6: true
  node: true
  browser: true
parserOptions:
  ecmaVersion: 8
rules:
  semi:
    - error
    - always
  disallowMultipleVarDecl: 0
  indent:
    - error
    - 2
  linebreak-style:
    - error
    - unix
